<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "npic_certificate"
 *
 * Auto generated by Extension Builder 2016-03-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NPIC Certificate Management (Web)',
	'description' => 'This is an extension use to help students search for their certificates on NPIC website (www.npic.edu.kh).',
	'category' => 'plugin',
	'author' => 'Sok Piseth',
	'author_email' => 'sokpiseth777@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);